# Application
spring.application.name=cabinet-medical

# Database Supabase
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.pwkmrsizrxlhnvtihazs
spring.datasource.password=cabinet2026
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Server
server.port=8080



# Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=equipemedicore@gmail.com
spring.mail.password=gvtbxranpaegteov
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG

# Supabase Storage Configuration
supabase.url=https://pwkmrsizrxlhnvtihazs.supabase.co

supabase.api.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3a21yc2l6cnhsaG52dGloYXpzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NTYzNzA3MSwiZXhwIjoyMDgxMjEzMDcxfQ.pHlrElsKCNwcIpH47l4iHd4aqSr3_Qoo4NdyLZTVPjA
supabase.storage.bucket=cabinet-documents-private