spring:
  application:
    name: cabinet-medical
  datasource:
    url: jdbc:postgresql://aws-1-eu-west-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
    username: postgres.pwkmrsizrxlhnvtihazs
    password: "cabinet2026"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: equipemedicore@gmail.com
    password: gvtbxranpaegteov
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

server:
  port: 8080

jwt:
  expiration: 14400000

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE